restart-prompt-title = 重启 { -brand-short-name }
restart-prompt-question = 您确定要重启 { -brand-short-name } 吗？
appmenuitem-restart-browser =
    .label = 重新启动
copy-url =
    .label = 复制标签链接
copy-all-urls =
    .label = 复制所有标签链接
unload-tab =
    .label = Unload Tab
open-all-private =
    .label = 在私有标签中打开所有
open-all-links-private =
    .label = 在私有标签中打开所有链接
open-private-tab =
    .label = 在新的私人选项卡中打开
new-private-tab =
    .label = 新建私人选项卡
    .tooltiptext = 打开新的私有标签页
open-link-private =
    .label = 在新的隐私选项卡中打开链接
status-bar =
    .label = 状态栏
tab-position-header = 标签栏位置
tab-bar-top-above =
    .label = 顶部地址栏
tab-bar-top-below =
    .label = 顶部地址栏
tab-bar-bottom-above =
    .label = 状态栏上方底部
tab-bar-bottom-below =
    .label = 底部状态栏下
tab-additional-header = 附加标签首选项
pinned-icon-only =
    .label = 收缩置顶的标签页以只显示站点图标
insert-after-current =
    .label = 在当前标签后插入新标签
insert-related-after-current =
    .label = 在当前标签后插入相关的新标签
dynamic-theme-header = 动态主题
dynamic-theme-dark =
    .label = 强制暗色模式
dynamic-theme-light =
    .label = 强制光线模式
dynamic-theme-auto =
    .label = 动态设置灯光/暗色模式
restart-header = 重启菜单项
restart-show-button =
    .label = 在面板界面中显示重启按钮
restart-purge-cache =
    .label = 浏览器重启时清理快速重启缓存
restart-require-confirmation =
    .label = 需要重新启动确认
tab-feature-header = Tab Context Menu
show-duplicate-tab =
    .label = Show duplicate tab menu item
show-copy-url =
    .label = 显示复制标签 url 菜单项
enable-copy-active-tab =
    .label = 仅从活动标签中复制 URL
show-copy-all-urls =
    .label = 显示复制所有标签页地址菜单项
show-unload-tab =
    .label = 显示卸载标签菜单项
statusbar-enabled =
    .label = 显示状态栏
statusbar-show-links =
    .label = 显示链接
statusbar-contrast-text =
    .label = 对比状态栏文本颜色
bookmarks-bar-position-header = 书签工具栏位置
bookmarks-position-top =
    .label = 顶端
bookmarks-position-bottom =
    .label = 底部
geolocation-api-header = 地理位置API
geolocation-description = 某些网站需要您的位置才能运行。 如果一个网站因无法找到您的位置而无法运行，请启用此选项并重试。
geolocation-api-enabled =
    .label = 启用
geolocation-api-disabled =
    .label = 禁用
send-referrer-header-0 =
    .label = 从不发送推荐信头
send-referrer-header-1 =
    .label = 仅当点击链接和类似元素时发送推荐信头
send-referrer-header-2 =
    .label = 发送所有请求的推荐信头(默认)
enable-webrtc-p2p =
    .label = 启用 WebRTC 节点连接
load-images =
    .label = 自动加载图像
enable-javascript =
    .label = 启用 JavaScript
webrtc-header = WebRTC 节点连接
ref-header = HTTP 推荐信头
statusbar-header = 状态栏
private-tab =
    .label =
        { $isPrivate ->
            [true] 退出私有选项卡
           *[false] 创建私人标签
        }
update-application-manual =
    .label = 从不检查更新（不建议）
    .accesskey = N
preferences-doh-setting-ultra =
    .label = 高级保护
    .accesskey = U
preferences-doh-ultra-desc = { -brand-short-name } 将通过Waterfox的隐私中继使用基于OHTTP的安全DNS，以提供最高级别的保护。
preferences-doh-ultra-detailed-desc-1 = 使用Waterfox的OHTTP中继，对DNS提供商隐藏DNS查询
preferences-doh-ultra-detailed-desc-2 = 在基于HTTPS的DNS之外提供额外的加密层
preferences-doh-ultra-detailed-desc-3 = 最大DNS隐私保护——没有人能看到你访问的网站
preferences-doh-ultra-fallback-mode = 回退行为：
preferences-doh-ultra-fallback-allowed = 如果安全DNS不可用，允许回退到系统DNS
preferences-doh-ultra-fallback-disabled = 永远不回退到系统DNS（如果安全DNS不可用，网站将无法加载）
pane-theme-title = 外观 & 体验
category-theme = { pane-theme-title }{ pane-theme-title }
animation-header = 动画
appearance-header = 外观
autohide-hidden-header = 自动影响
bookmark-header = 书签栏
center-header = 中心
font-header = 字体
full-screen-header = 全屏
icons-header = 图标
interface-component-header = 组件接口
media-player-header = 媒体播放器
nav-bar-header = 导航条
panels-header = 面板
rounding-header = 圆角
sidebar-header = 侧栏
tab-bar-header = 菜单
theme-header = 主题
preset-title = 默认值
lepton-style =
    .label = Lepton 风格
proton-style =
    .label = Proton 风格
waterfox-defaults =
    .label = Waterfox 默认
auto-blur-tabs =
    .label = 标签自动模糊
auto-hide-back =
    .label = 自动隐藏后退按钮
auto-hide-bookmarkbar =
    .label = 自动隐藏书签栏
auto-hide-forward =
    .label = 自动隐藏前进按钮
auto-hide-navbar =
    .label = 自动隐藏导航栏
auto-hide-pageaction =
    .label = 自动隐藏页面操作
auto-hide-sidebar =
    .label = 自动隐藏侧栏
auto-hide-tabbar =
    .label = 自动隐藏标签栏
auto-hide-tabs =
    .label = 自动隐藏标签页
center-navbar-text =
    .label = 使导航栏文字居中
center-tab-content =
    .label = 使页面内容居中
hide-all-icons =
    .label = 隐藏所有图标
hide-bookmarkbar-icon =
    .label = 隐藏书签栏图标
hide-bookmarkbar-label =
    .label = 隐藏书签栏标签
hide-disabled-menuitems =
    .label = 隐藏禁用的菜单项
hide-sidebar-header =
    .label = 隐藏侧栏标题
hide-tab-icons =
    .label = 隐藏标签页图标
hide-urlbar-iconbox =
    .label = 隐藏地址栏图标框
monospace-font =
    .label = 对页面启用等宽字体
monospace-font-theme =
    .label = 对主题启用等宽字体
show-mac-menu-icons =
    .label = 显示 Mac 菜单图标
show-menu-icons =
    .label = 显示菜单图标
square-button-edges =
    .label = 方块按钮边角
square-checkbox =
    .label = 方形复选框
square-field =
    .label = 方形条目字段边角
center-tab-label =
    .label = 仅居中标签页标签
close-button-hover =
    .label = 在打开多个标签页时当悬停于选定标签页时显示关闭标签页按钮
pane-tree-title = 树状垂直标签页
browser-layout-tree-vertical-tabs =
    .label = 树状垂直标签页
sidebar-tree-vertical-tabs =
    .label = 树状垂直标签页
tree-header = 树状垂直标签页
tree-sticky-active-tab =
    .label = 活动标签页
    .accesskey = k
tree-successor-tab-control-level-caption =
    .value = 在当前标签页作为最后的子标签页关闭时
    .accesskey = h
tree-successor-tab-control-level-in-tree =
    .label = 聚焦到树中的上一个标签页
tree-successor-tab-control-level-never =
    .label = 始终聚焦到下一个标签页 (遵循浏览器或其它扩展的控制)
tree-successor-tab-control-level-simulate-default =
    .label = 始终聚焦到下一个标签页
enable-menu-transparency =
    .label = 启用菜单透明
enable-panel-transparency =
    .label = 启用面板透明化
enable-waterfox-theme-0 =
    .label = 在所有主题上启用 Waterfox 主题定制
enable-waterfox-theme-1 =
    .label = 在 Waterfox 主题上启用 Waterfox 主题定制
enable-waterfox-theme-2 =
    .label = 禁用 Waterfox 主题定制
full-panel-strip =
    .label = 全宽应用菜单分隔符
remove-panel-strip =
    .label = 移除彩色应用菜单分隔符
square-menu-item =
    .label = 方形上下文菜单项边角
square-menu-panel =
    .label = 方形应用菜单面板边角
square-menu-popup =
    .label = 方形上下文菜单边角
square-panel-item =
    .label = 方形应用菜单项边角
square-tab-edges =
    .label = 方形标签页边角
tab-context-line =
    .label = 标签页上下文行
telemetry-page-subtitle = Waterfox 不收集有关您的安装的遥测数据 - 当构建浏览器时禁用了任何的遥测模块。您在浏览中所作所为仅您自己知道。
telemetry-privacy-policy = 隐私政策
tabbrowser-confirm-session-restore-checkbox = 打开先前的窗口和标签页
tree-appearance-header = 外观
tree-faviconize-pinned-tabs =
    .label = 仅用标签页的图标显示固定的标签页
    .accesskey = S
tree-sticky-sharing-tab =
    .label = 标签页分享摄像头/麦克风/屏幕
    .accesskey = g
tree-sticky-sound-playing-tab =
    .label = 声音播放标签页
    .accesskey = y
tree-behavior-header = 标签页的树状视图
tree-auto-collapse-expand-subtree-on-attach =
    .label = 在出现新树时，自动折叠其它的
    .accesskey = c
tree-auto-collapse-expand-subtree-on-select =
    .label = 当标签页获得焦点时，自动展开它所在的树并折叠其它的
    .accesskey = x
